# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ebb25654dd00e6d8bf833ab8b15e9a6"
application_url = "https://mario-aged-passenger-speeds.trycloudflare.com"
embedded = true
name = "mansi-app-dev"
handle = "mansi-app-dev"

[webhooks]
api_version = "2023-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://mario-aged-passenger-speeds.trycloudflare.com/auth/callback",
  "https://mario-aged-passenger-speeds.trycloudflare.com/auth/shopify/callback",
  "https://mario-aged-passenger-speeds.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "mansi-meroxio-dev.myshopify.com"
automatically_update_urls_on_dev = true
