# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "220aaa3f99ef967f2b678b1b63cdd57a"
application_url = "https://scroll2top.onkra.online/"
embedded = true
name = "MeroxIO Scroll 2 Top"
handle = "meroxio-scroll-2-top"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://scroll2top.onkra.online/auth/callback",
  "https://scroll2top.onkra.online/auth/shopify/callback",
  "https://scroll2top.onkra.online/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
